### ISSUE TITLE
ng-packagr

### ISSUE THREAD

**Issue by bevrard** [clickup/ngx-esbuild#21]
### Description

Would it be possible to make it work with ng-packgr? (in watch mode?)

Kind regards

**Comment by mattlewis92** [comment]
Good question! Unfortunately this approach wouldn't work for libraries, to build an angular library requires the angular compiler, which is built on top of typescript. But this implementation is fast due to it not using typescript, so by association we also cannot use the angular compiler. Given the tools we have available today,`ng-packagr` is probably about as fast as it could be.

But you may have some luck, by changing the `compilationMode` in your libraries tsconfig to `experimental-local`, which may allow faster builds. I haven't tried this myself though so it may not work, and is still considered experimental.
